name: tomo-reg-env
channels:
  - conda-forge
  - pytorch
  - defaults
  - anaconda
dependencies:
  - matplotlib
  - numpy<2
  - scipy
  - opencv
  - python
  - ipykernel
  - torchaudio=2.2.0
  - torchvision=0.17.0
  - pytorch=2.2.0
  - cpuonly
  - pandas
  - statsmodels
